package Model;
// Generated 19 Jan, 2020 1:54:58 PM by Hibernate Tools 3.6.0



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer ids;
     private String name;
     private int quantity;
     private int price;
     private String seller;
     private String user;

    public Orders() {
    }

    public Orders(String name, int quantity, int price, String seller, String user) {
       this.name = name;
       this.quantity = quantity;
       this.price = price;
       this.seller = seller;
       this.user = user;
    }
   
    public Integer getIds() {
        return this.ids;
    }
    
    public void setIds(Integer ids) {
        this.ids = ids;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getSeller() {
        return this.seller;
    }
    
    public void setSeller(String seller) {
        this.seller = seller;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }




}


