package Model;
// Generated 10 Aug, 2019 10:06:46 AM by Hibernate Tools 3.2.1.GA



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String password;
     private String name;
     private String address;
     private String phNo;

    public Student() {
    }

    public Student(String userName, String password, String name, String address, String phNo) {
       this.userName = userName;
       this.password = password;
       this.name = name;
       this.address = address;
       this.phNo = phNo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhNo() {
        return this.phNo;
    }
    
    public void setPhNo(String phNo) {
        this.phNo = phNo;
    }




}


